[package]
authors = ["Adam <adamsimeth@gmail.com>"]
name = "admiral"
version = "1.1.0"

[dependencies]
clap = "2.33.0"
serde = "1.0.101"
serde_derive = "1.0.101"
threadpool = "1.7.1"
toml = "0.5.3"
chan = "0.1.23"
chan-signal = "0.3.3"
